[package]
name = "rust-wasm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parity-wasm = "0.42"
wasmer = "2.0.0"
anyhow = "1.0.43"
